### ISSUE TITLE
Research in wiki returning empty array

### ISSUE THREAD

**Issue by ciddim** [GLO3102/UBeat#28]
http://ubeat.herokuapp.com/unsecure/albums/325483

Documentation in the 2.6 Albums wiki is returning an empty array.

And the bottom link for the songs related to this album returns an unexisting value. (-1)

**Comment by wfortin** [comment]
Fixed, thank you !
https://github.com/GLO3102/UBeat/wiki/2.6-Albums#get-albumsid
