### ISSUE TITLE
Following subdocuments array items invalid id

### ISSUE THREAD

**Issue by alexbrillant** [GLO3102/UBeat#31]
https://github.com/GLO3102/UBeat/wiki/2.5-Utilisateurs#post-follow

POST /follow should push a new follower with the right user id. 

Mongoose is creating a _id property automatically for subdocuments array items...

Workaround : 
https://stackoverflow.com/questions/17254008/stop-mongoose-from-creating-id-property-for-sub-document-array-items

**Comment by vseguin** [comment]
Duplicate, closing
