### ISSUE TITLE
Erreur 503 lors du call DELETE  /follow

### ISSUE THREAD

**Issue by Caron300** [GLO3102/UBeat#35]
J'ai une erreur 503 en callant http://ubeat.herokuapp.com/follow/5abb9e7bc44b0800048c1cde 
Body de la requête:
{
	"id": "5abd0a7040617c00047267a3"
}

Retour : 
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">
        <title>Application Error</title>
        <style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
    </head>
    <body>
        <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
    </body>
</html>

**Comment by vseguin** [comment]
Should be fixed with next deploy.
