### ISSUE TITLE
Fetching followers doesn't give you the actual user id

### ISSUE THREAD

**Issue by medmouine** [GLO3102/UBeat#36]
When you fetch the list of followers with the get users/:id in the array of followers all you have is the name, email and their own followers array (which is always empty). the only id i could find is the _id generated by mongo and it's clearly not the right one as whenever i use it to redirect the user to a profile the server responds with a 404 error.

**Comment by wfortin** [comment]
On it.

**Comment by vseguin** [comment]
Should be fixed with next deploy.
