### ISSUE TITLE
Ajout de track retourne la playlist avec un _id pas de contenu

### ISSUE THREAD

**Issue by EllanTseyeth** [GLO3102/UBeat#42]
{
    "owner": {
        "email": "team21@ulaval.ca",
        "id": "5bc527e286d15d00046e4410"
    },
    "name": "Tracker",
    "tracks": [
        {
            "_id": "5bcca256845f050004646532"
        },
        {
            "_id": "5bcca2ad845f050004646534"
        },
        {
            "_id": "5bcca392845f050004646536"
        },
        {
            "_id": "5bcca5eb845f050004646538"
        },
        {
            "_id": "5bcca5fd845f05000464653a"
        }
    ],
    "id": "5bcc934c845f050004646526"
}

mon Postman dump.

POST /playlists/5bcc934c845f050004646526/tracks/ HTTP/1.1
Host: ubeat.herokuapp.com
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YmM1MjdlMjg2ZDE1ZDAwMDQ2ZTQ0MTAiLCJleHAiOjE1NDAyMjAwMTg0OTh9.nJtHEGVPtCYwtBNKkE_sUhBAwBybn0HPM91mMZYralI
Content-Type: application/json
cache-control: no-cache
Postman-Token: 13bfdcc6-2e99-40cd-9136-af5f43d639b5
{
	"track" : {
    "artistId": 889780,
    "collectionId": 947701030,
    "trackId": 947701034,
    "artistName": "Red Hot Chili Peppers",
    "collectionName": "Greatest Hits",
    "trackName": "Give It Away",
    "collectionCensoredName": "Greatest Hits",
    "trackCensoredName": "Give It Away",
    "artistViewUrl": "https://itunes.apple.com/us/artist/red-hot-chili-peppers/889780?uo=4",
    "collectionViewUrl": "https://itunes.apple.com/us/album/give-it-away/947701030?i=947701034&uo=4",
    "trackViewUrl": "https://itunes.apple.com/us/album/give-it-away/947701030?i=947701034&uo=4",
    "previewUrl": "https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music3/v4/c7/52/9f/c7529f68-4721-c133-334c-ff2754bc30ec/mzaf_940065862116637667.plus.aac.p.m4a",
    "artworkUrl30": "https://is4-ssl.mzstatic.com/image/thumb/Music3/v4/87/98/aa/8798aa47-233e-b3a4-8154-3a4f4dee0209/source/30x30bb.jpg",
    "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Music3/v4/87/98/aa/8798aa47-233e-b3a4-8154-3a4f4dee0209/source/60x60bb.jpg",
    "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Music3/v4/87/98/aa/8798aa47-233e-b3a4-8154-3a4f4dee0209/source/100x100bb.jpg",
    "collectionPrice": 12.99,
    "trackPrice": 1.29,
    "releaseDate": "1991-09-04T07:00:00.000Z",
    "discCount": 1,
    "discNumber": 1,
    "trackCount": 16,
    "trackNumber": 2,
    "trackTimeMillis": 284870,
    "country": "USA",
    "currency": "USD",
    "primaryGenreName": "Alternative"
}
}------WebKitFormBoundary7MA4YWxkTrZu0gW--

Fais-je quelque chose d'incorrect ou c'est vraiment un bug?

**Comment by EllanTseyeth** [comment]
En unsecured, ça fait pareille:
`fetch("http://ubeat.herokuapp.com/unsecure/playlists/5bd8b79bc8acfe0004adefd2/tracks?owner=team21@ulaval.ca", {"credentials":"omit","headers":{"accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8"},"referrer":"http://localhost:8080/","referrerPolicy":"no-referrer-when-downgrade","body":"{\"track\":{\"wrapperType\":\"track\",\"kind\":\"song\",\"artistId\":\"171366\",\"collectionId\":717552717,\"trackId\":\"717552719\",\"artistName\":\"Frank Sinatra\",\"collectionName\":\"Nothing But the Best (Remastered)\",\"trackName\":\"The Best Is Yet to Come (feat. Count Basie and His Orchestra)\",\"collectionCensoredName\":\"Nothing But the Best (Remastered)\",\"trackCensoredName\":\"The Best Is Yet to Come (feat. Count Basie and His Orchestra)\",\"artistViewUrl\":\"https://itunes.apple.com/us/artist/frank-sinatra/171366?uo=4\",\"collectionViewUrl\":\"https://itunes.apple.com/us/album/the-best-is-yet-to-come-feat-count-basie-and-his-orchestra/717552717?i=717552719&uo=4\",\"trackViewUrl\":\"https://itunes.apple.com/us/album/the-best-is-yet-to-come-feat-count-basie-and-his-orchestra/717552717?i=717552719&uo=4\",\"previewUrl\":\"https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/AudioPreview62/v4/f3/9d/57/f39d57dd-c53c-c650-22aa-8350f0ccf9c6/mzaf_2639113511084837324.plus.aac.p.m4a\",\"artworkUrl30\":\"https://is3-ssl.mzstatic.com/image/thumb/Music6/v4/89/44/0d/89440d19-8dae-666e-51e1-268b086f3f49/source/30x30bb.jpg\",\"artworkUrl60\":\"https://is3-ssl.mzstatic.com/image/thumb/Music6/v4/89/44/0d/89440d19-8dae-666e-51e1-268b086f3f49/source/60x60bb.jpg\",\"artworkUrl100\":\"https://is3-ssl.mzstatic.com/image/thumb/Music6/v4/89/44/0d/89440d19-8dae-666e-51e1-268b086f3f49/source/100x100bb.jpg\",\"collectionPrice\":11.99,\"trackPrice\":1.29,\"releaseDate\":\"1964-08-01T07:00:00Z\",\"collectionExplicitness\":\"notExplicit\",\"trackExplicitness\":\"notExplicit\",\"discCount\":1,\"discNumber\":1,\"trackCount\":22,\"trackNumber\":2,\"trackTimeMillis\":175813,\"country\":\"USA\",\"currency\":\"USD\",\"primaryGenreName\":\"Vocal Pop\",\"isStreamable\":true}}","method":"POST","mode":"cors"});`

Le retour est ceci:

`{"owner":{"email":"team21@ulaval.ca","id":"5bc527e286d15d00046e4410"},"name":"Mew2","tracks":[{"_id":"5bd8b7b4c8acfe0004adefd4"},{"_id":"5bd8fe8f493b4a00042331d3"},{"_id":"5bd8fe8f493b4a00042331d5"},{"_id":"5bd8fe8f493b4a00042331d7"},{"_id":"5bd8fe8f493b4a00042331d9"},{"_id":"5bd92286493b4a00042331db"},{"_id":"5bd92287493b4a00042331dd"},{"_id":"5bd9250f493b4a00042331e7"}],"id":"5bd8b79bc8acfe0004adefd2"}`

**Comment by wfortin** [comment]
Je regarde ça

**Comment by wfortin** [comment]
Je viens de créer une playlist de cette façon:

`POST https://ubeat.herokuapp.com/unsecure/playlists`
Body:
```JSON
{
  "name": "Playlist name",
  "owner": "william+29@pleo.io" 
}
```

Ensuite j'ai ajouté une chanson:

`POST https://ubeat.herokuapp.com/unsecure/playlists/5bda16c5493b4a0004233298/tracks`
Body:
```JSON
{
    "wrapperType": "track",
    "kind": "song",
    "artistId": 356545647,
    "collectionId": 409001929,
    "trackId": 409001935,
    "artistName": "Skrillex",
    "collectionName": "Scary Monsters and Nice Sprites",
    "trackName": "Scary Monsters and Nice Sprites",
    "collectionCensoredName": "Scary Monsters and Nice Sprites",
    "trackCensoredName": "Scary Monsters and Nice Sprites",
    "artistViewUrl": "https://itunes.apple.com/us/artist/skrillex/356545647?uo=4",
    "collectionViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
    "trackViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
    "previewUrl": "https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music/2a/79/01/mzm.uiaapnbf.aac.p.m4a",
    "artworkUrl30": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/30x30bb.jpg",
    "artworkUrl60": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/60x60bb.jpg",
    "artworkUrl100": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/100x100bb.jpg",
    "collectionPrice": 7.99,
    "trackPrice": 1.29,
    "releaseDate": "2010-10-22T07:00:00Z",
    "collectionExplicitness": "explicit",
    "trackExplicitness": "notExplicit",
    "discCount": 1,
    "discNumber": 1,
    "trackCount": 9,
    "trackNumber": 2,
    "trackTimeMillis": 243354,
    "country": "USA",
    "currency": "USD",
    "primaryGenreName": "Dance",
    "isStreamable": true
}
```

Ensuite `GET https://ubeat.herokuapp.com/unsecure/playlists/5bda16c5493b4a0004233298` me retourne la playlist avec les bons champs:
```JSON
{
    "owner": {
        "name": "william",
        "email": "william+29@pleo.io",
        "id": "5bd75ac77c7ac40004d64cdd"
    },
    "name": "Playlist name",
    "tracks": [
        {
            "_id": "5bda16d4493b4a000423329a",
            "artistId": 356545647,
            "collectionId": 409001929,
            "trackId": 409001935,
            "artistName": "Skrillex",
            "collectionName": "Scary Monsters and Nice Sprites",
            "trackName": "Scary Monsters and Nice Sprites",
            "collectionCensoredName": "Scary Monsters and Nice Sprites",
            "trackCensoredName": "Scary Monsters and Nice Sprites",
            "artistViewUrl": "https://itunes.apple.com/us/artist/skrillex/356545647?uo=4",
            "collectionViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
            "trackViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
            "previewUrl": "https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music/2a/79/01/mzm.uiaapnbf.aac.p.m4a",
            "artworkUrl30": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/30x30bb.jpg",
            "artworkUrl60": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/60x60bb.jpg",
            "artworkUrl100": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/100x100bb.jpg",
            "collectionPrice": 7.99,
            "trackPrice": 1.29,
            "releaseDate": "2010-10-22T07:00:00.000Z",
            "discCount": 1,
            "discNumber": 1,
            "trackCount": 9,
            "trackNumber": 2,
            "trackTimeMillis": 243354,
            "country": "USA",
            "currency": "USD",
            "primaryGenreName": "Dance"
        }
    ],
    "id": "5bda16c5493b4a0004233298"
}
```
Je ne vois pas vraiment la différence avec tes calls mais ça fonctionne pour moi dans Postman

**Comment by EllanTseyeth** [comment]
Hmmm intéressant,


La seule différence est que j'ai créé les playlist et on fait l'ajout en mode sécure!

Merci,
Joel Lamothe
BAC Sc. A. Informatique
111 175 421



On Oct 31, 2018 5:01 PM, William Fortin <notifications@github.com> wrote:



Je viens de créer une playlist de cette façon:
POST https://ubeat.herokuapp.com/unsecure/playlists
Body:

{
  "name": "Playlist name",
  "owner": "william+29@pleo.io" 
}

Ensuite j'ai ajouté une chanson:
POST https://ubeat.herokuapp.com/unsecure/playlists/5bda16c5493b4a0004233298/tracks
Body:

{
    "wrapperType": "track",
    "kind": "song",
    "artistId": 356545647,
    "collectionId": 409001929,
    "trackId": 409001935,
    "artistName": "Skrillex",
    "collectionName": "Scary Monsters and Nice Sprites",
    "trackName": "Scary Monsters and Nice Sprites",
    "collectionCensoredName": "Scary Monsters and Nice Sprites",
    "trackCensoredName": "Scary Monsters and Nice Sprites",
    "artistViewUrl": "https://itunes.apple.com/us/artist/skrillex/356545647?uo=4",
    "collectionViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
    "trackViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
    "previewUrl": "https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music/2a/79/01/mzm.uiaapnbf.aac.p.m4a",
    "artworkUrl30": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/30x30bb.jpg",
    "artworkUrl60": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/60x60bb.jpg",
    "artworkUrl100": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/100x100bb.jpg",
    "collectionPrice": 7.99,
    "trackPrice": 1.29,
    "releaseDate": "2010-10-22T07:00:00Z",
    "collectionExplicitness": "explicit",
    "trackExplicitness": "notExplicit",
    "discCount": 1,
    "discNumber": 1,
    "trackCount": 9,
    "trackNumber": 2,
    "trackTimeMillis": 243354,
    "country": "USA",
    "currency": "USD",
    "primaryGenreName": "Dance",
    "isStreamable": true
}

Ensuite GET https://ubeat.herokuapp.com/unsecure/playlists/5bda16c5493b4a0004233298 me retourne la playlist avec les bons champs:

{
    "owner": {
        "name": "william",
        "email": "william+29@pleo.io",
        "id": "5bd75ac77c7ac40004d64cdd"
    },
    "name": "Playlist name",
    "tracks": [
        {
            "_id": "5bda16d4493b4a000423329a",
            "artistId": 356545647,
            "collectionId": 409001929,
            "trackId": 409001935,
            "artistName": "Skrillex",
            "collectionName": "Scary Monsters and Nice Sprites",
            "trackName": "Scary Monsters and Nice Sprites",
            "collectionCensoredName": "Scary Monsters and Nice Sprites",
            "trackCensoredName": "Scary Monsters and Nice Sprites",
            "artistViewUrl": "https://itunes.apple.com/us/artist/skrillex/356545647?uo=4",
            "collectionViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
            "trackViewUrl": "https://itunes.apple.com/us/album/scary-monsters-and-nice-sprites/409001929?i=409001935&uo=4",
            "previewUrl": "https://audio-ssl.itunes.apple.com/apple-assets-us-std-000001/Music/2a/79/01/mzm.uiaapnbf.aac.p.m4a",
            "artworkUrl30": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/30x30bb.jpg",
            "artworkUrl60": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/60x60bb.jpg",
            "artworkUrl100": "http://is1.mzstatic.com/image/thumb/Music71/v4/12/53/72/12537299-bf43-e7ec-964a-097da7df1d66/source/100x100bb.jpg",
            "collectionPrice": 7.99,
            "trackPrice": 1.29,
            "releaseDate": "2010-10-22T07:00:00.000Z",
            "discCount": 1,
            "discNumber": 1,
            "trackCount": 9,
            "trackNumber": 2,
            "trackTimeMillis": 243354,
            "country": "USA",
            "currency": "USD",
            "primaryGenreName": "Dance"
        }
    ],
    "id": "5bda16c5493b4a0004233298"
}

Je ne vois pas vraiment la différence avec tes calls mais ça fonctionne pour moi dans Postman
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.

**Comment by EllanTseyeth** [comment]
Mes collègues viennent de me dire qu'ils ont touvés le problème, une paire de curly braces de trop!
