### ISSUE TITLE
403 Forbidden en secured et en unsecured pour faire la recherche.

### ISSUE THREAD

**Issue by EllanTseyeth** [GLO3102/UBeat#43]
```
GET /search/albums HTTP/1.1
Host: ubeat.herokuapp.com
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YmM1MjdlMjg2ZDE1ZDAwMDQ2ZTQ0MTAiLCJleHAiOjE1NDEyMTE1MDYxNjd9.Dux5Rv-zAHo2EjwyS8V0HrSj54k5gav8cuvSjDiO5BY
cache-control: no-cache
Postman-Token: b1b8412f-397b-492c-ac37-c1afb6b3d618

```

On load un sample de tunes et d'artistes dans notre page d'accueil et on reçoit des forbidden autant en unsecured qu'en secured...

Tout à l'heure ça fonctionnait et sans faire de changement ça a commencé à exploser...

![image](https://user-images.githubusercontent.com/25628380/47890384-042cc800-de25-11e8-8a7a-2438de262647.png)

Pourtant je suis encore capable de loader les playlists dans une autre de nos pages. mais pas de rechercher.

**Comment by EllanTseyeth** [comment]
Ce matin à la place c'Est `GET https://ubeat.herokuapp.com/search/albums?q=Listen 401 (Unauthorized)` qu'on obtient! et même nos playlist font le 401 cette fois-ci

**Comment by wfortin** [comment]
Est-ce que tu fait la vérification de la validité de ton token avant de faire des requêtes?
https://github.com/GLO3102/UBeat/wiki/2.3-Token-info
Cette requête retourne:

401
```
{
    "errorCode": "ACCESS_DENIED",
    "message": "Access token is expired"
}
```
Si le token n'est plus valide. Le token a une durée limité de 1h, tu doit donc faire la mécanique de vérification de token, si le token est expiré tu doit demander à l'utilisateur de se reconnecter pour renouveller le token. Le token n'est pas demandé pour le livrable 2, donc assurez vous que ça ne cause pas de problème pour la correction.

Pour ce qui est du 403, il semblerait qu'iTunes aurait "throttlé" nos requêtes, il y a possiblement trop de requêtes en simultané. Le problème semble être résolu maintenant. Si le problème persiste vous pouvez rouler l'API en local, ce qui rendra les requête sur un autre IP et contournera le throttling.

Bon succès.
