### ISSUE TITLE
PUT de playlists/:id "efface" les tracks (secure)

### ISSUE THREAD

**Issue by DanP96** [GLO3102/UBeat#44]
j'ai fait des tests dans postman et on dirait que losrqu'on modifie le nom d'une playlist, le nom change, mais l'API ne retourne pas d'array Tracks et lorsqu'on get la ou toutes les playlists, les tracks n'existe plus pour cette playlist (mais le nom change pour le modifié)?

**Comment by wfortin** [comment]
Un put nécessite l'entièreté du payload. Ce n'est pas un patch.

**Comment by DanP96** [comment]
oups my bad! merci!
