### ISSUE TITLE
GET /logout vs POST /logout

### ISSUE THREAD

**Issue by ecfy** [GLO3102/UBeat#48]
En regardant la documentation, j'ai remarqué que le logout se fait en GET plutôt qu'en POST. Puisque c'était la première fois que je voyais cela (j'utilise toujours un POST pour le logout en général), je me suis questionné un peu et fait une recherche Google, qui m'a pointé sur [cette réponse sur StackOverflow.](https://stackoverflow.com/a/14587231/7774890)

Afin de suivre les meilleures pratiques modernes, serait-il préférable de remplacer le GET /logout par un POST /logout?

**Comment by vseguin** [comment]
Bon point - j'accepte les PRs :)

**Comment by ecfy** [comment]
J'vais faire ça dès que j'ai un p'tit lousse! Considérant que la gestion des sessions ne se fait pas vraiment avant le 3e livrable, juges-tu nécessaire de conserver le GET /logout en tant que _deprecated_ ?
